name: Doabot
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.12.12
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cohere==5.15.0
      - discord-py==2.3.2
      - fastavro==1.12.1
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==1.1.1
      - idna==3.11
      - multidict==6.7.0
      - packaging==25.0
      - propcache==0.4.1
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-dotenv==1.0.1
      - pyyaml==6.0.3
      - requests==2.32.5
      - shellingham==1.5.4
      - sniffio==1.3.1
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - types-requests==2.32.4.20250913
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - yarl==1.22.0
prefix: /home/kenshirotm/miniconda3/envs/Doabot
